const chokidar = require('chokidar');
const { exec } = require('child_process');
const fs = require('fs');
const xlsx = require('xlsx');

console.log('Watching for file changes to auto-push to GitHub...');

// Watch for file changes. Ignore dotfiles, node_modules, and files generated by this script.
const watcher = chokidar.watch('.', {
  ignored: /(^|[\/\\])\..|node_modules|autopush\.js|data\.js|data\.json/, 
  persistent: true
});

let isProcessing = false;
let timeout = null;

const processAndPush = () => {
  if (isProcessing) return;
  isProcessing = true;
  console.log('Changes detected! Updating dashboard data...');

  try {
    // Read new excel data
    if (fs.existsSync('Data_Master.xlsx')) {
        const wb = xlsx.readFile('Data_Master.xlsx');
        const data = xlsx.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]);
        const jsonDataString = JSON.stringify(data);
        
        // Generate data.js which is loaded by index.html
        fs.writeFileSync('data.js', 'window.rawData = ' + jsonDataString + ';');
        console.log('Data successfully embedded into data.js.');
    }
    
    // Regenerate finance_data.js
    if (fs.existsSync('parse_finance.js')) {
        exec('node parse_finance.js', (err) => {
            if (err) console.error('Failed to update finance_data:', err.message);
            else console.log('Finance data successfully updated.');
        });
    }
    
    // Use powershell syntax for multiple commands using `;`
    exec('git add . ; git commit -m "Auto update data/files" ; git push origin main', { shell: 'powershell.exe' }, (error, stdout, stderr) => {
      if (error) {
        console.log('Push finished with message (might be up to date or network error):', error.message);
      } else {
        console.log('Successfully pushed changes to GitHub.');
        console.log(stdout);
      }
      isProcessing = false;
    });

  } catch (err) {
    console.error('Error processing excel file:', err.message);
    isProcessing = false;
  }
};

watcher.on('change', path => {
  console.log(`File ${path} has been changed`);
  clearTimeout(timeout);
  // Debounce for 3 seconds to avoid multiple rapid pushes
  timeout = setTimeout(processAndPush, 3000);
});
